### ISSUE TITLE
Openfire 4.8.0 compatbility

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-threaddump-plugin#12]
When loaded in Openfire 4.8.0, this plugin logs this to stdout:

```
Exception in thread "ThreadDump-Timer-1" java.lang.NoSuchMethodError: 'org.apache.mina.transport.socket.nio.NioSocketAcceptor org.jivesoftware.openfire.spi.ConnectionListener.getSocketAcceptor()'
        at org.igniterealtime.openfire.plugin.threaddump.evaluator.CoreThreadPoolsEvaluator.checkPools(CoreThreadPoolsEvaluator.java:63)
        at org.igniterealtime.openfire.plugin.threaddump.evaluator.CoreThreadPoolsEvaluator.shouldCreateThreadDump(CoreThreadPoolsEvaluator.java:35)
        at org.igniterealtime.openfire.plugin.threaddump.DumpCheckTimerTask.run(DumpCheckTimerTask.java:97)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by akrherz** [comment]
Just denoting that 694896e91 bumped this plugin to require 4.8.0, but code changes are still needed.

**Comment by guusdk** [comment]
This effort depends on https://igniterealtime.atlassian.net/browse/OF-2789

**Comment by guusdk** [comment]
Rather than waiting for OF-2789, this plugin should be released, with the broken functionality disabled.

I've created a new ticket to re-instate the broken functionality: https://github.com/igniterealtime/openfire-threaddump-plugin/issues/16
